- hosts: localhost
  connection: local
  tasks:
    - name: Import VPC Variables
      include_ vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpv_net: 
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout  

